export const product = [
    {id:0, name:"Banner And Signage", price:'20$',},
    {id:1, name:"Bussiess Cards", price:'30$'},
    {id:2, name:"Calander", price:'30$'},
    {id:3, name:"bag-design", price:'30$'},
    {id:4, name:"Panaflex Design", price:'30$'},
    {id:5, name:"Poster", price:'30$'},
    {id:6, name:"Borshers", price:'30$'},
    {id:7, name:"Mug Printing", price:'30$'},
    {id:8, name:"T-Shirt Printing", price:'30$'},
    {id:9, name:"Key-Ring Printing", price:'30$'},
    {id:10, name:"Four color sticker Printing" ,price:'30$'},
    {id:11, name:"Logo Design", price:'30$'},
    {id:12, name:"Website Designing", price:'30$'},
    {id:13, name:"Envelops", price:'30$'},
    {id:14, name:"Notepads", price:'30$'},
    {id:15, name:"File Covers", price:'30$'},
    {id:16, name:"Note Pads", price:'30$'},
    {id:17, name:"Books", price:'30$'},
    {id:18, name:"Shields", price:'30$'},
    {id:19, name:"Stamps", price:'30$'}
];